error:
  whitelabel:
    enabled: false

amazon:
  associate_id: hong

logging:
  level:
    root: INFO
    
---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost:3306/readinglist
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: none
